Added sodium bicarbonate chemical recipe
bruberu/GregTechFoodOption pull request #76
Opened 2024-08-11 21:46 UTC by 1point7point4

2024-08-11 21:50 UTC, 1point7point4 commented
not sure why it's using two of my accounts but it's fine

2024-08-12 04:30 UTC, bruberu requested changes

2024-08-12 04:30 UTC, bruberu commented on src/main/java/gregtechfoodoption/recipe/chain/BritishChain.java
> +        RecipeMaps.CHEMICAL_RECIPES.recipeBuilder().EUt(30).duration(50)
While the formula Na2CO3 + CO2 + H2O -> 2NaHCO3 is stoichiometrically correct, this doesn't follow GTCEu's conventions. Particularly, the fluids should all be multiples of 1000, and the dusts should be used in quantities that are a multiple of the number of atoms that make up each molecule, just like most GTCEu recipes. At the very least, this recipe does seem to exist in real life.

2024-08-13 16:20 UTC, bruberu approved these changes

2024-08-13 16:21 UTC, merged